Update Jquery fix for Letsbeclear
UCF/LetsBeClear pull request #2
Opened 2021-01-27 19:36 UTC by vinhtvu2

Remove older version of JQuery to enqueue newer version.

Copied code fix from this repo:
https://github.com/LaughingSamurai/UCFDiversity/commit/e513d292fe5e81cb7380339fab58925fd441e76f

2021-01-27 20:03 UTC, cjg89 requested changes

2021-01-27 20:03 UTC, cjg89 commented on templates/head.php
>    <script>window.jQuery || document.write('<script src="<?php echo get_template_directory_uri(); ?>/assets/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
jQuery 1.11.2 inclusion should be removed here

2021-01-27 20:03 UTC, cjg89 commented on lib/cleanup.php
> -function roots_clean_style_tag($input) {
Is this code deletion necessary if the only intended change is a jQuery bump?

2021-01-27 20:03 UTC, cjg89 commented on lib/init.php
> +  // add_editor_style('assets/css/editor-style.css');
Is this code commenting necessary if the only intended change is a jQuery bump?

2021-01-27 20:03 UTC, cjg89 commented on templates/head.php
> +  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
Unless I'm missing something, it doesn't look like this site uses Athena--are the tether.js and Athena JS inclusions necessary?

2021-01-28 16:30 UTC, vinhtvu2 commented on templates/head.php
>    <script>window.jQuery || document.write('<script src="<?php echo get_template_directory_uri(); ?>/assets/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
Removed on new push.

2021-01-28 16:32 UTC, vinhtvu2 commented on lib/cleanup.php
> -function roots_clean_style_tag($input) {
This code removal was necessary after updating beyond WordPress 5.3:
https://hirecollin.com/2019/11/how-to-fix-broken-sage-roots-themes-that-broke-in-wordpress-5-3-0/

2021-01-28 16:32 UTC, vinhtvu2 commented on lib/init.php
> +  // add_editor_style('assets/css/editor-style.css');
This is unnecessary removal. Added back.

2021-01-28 16:33 UTC, rjucf approved these changes

2021-01-28 16:33 UTC, vinhtvu2 commented on templates/head.php
> +  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
Removed Tether and Athena.

2021-01-28 16:36 UTC, vinhtvu2 commented
Fixed some of the issues Jo brought up in the PR :-)
Thanks Jo!

2021-01-28 16:38 UTC, cadie approved these changes

2021-01-28 16:45 UTC, jmbarne3 approved these changes

2021-01-28 17:06 UTC, cjg89 approved these changes

2021-01-28 17:13 UTC, merged